In [9]:
from csv import reader
from csv import writer
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandasql as ps

In [127]:
price = pd.read_csv("asx-equity-price.csv")
price.head()

  ticker      date   open   high    low  close  volume
0    AAA  19970102  2.430  2.450  2.420  2.430   62508
1    AAD  19970102  0.740  0.760  0.740  0.750   10722
2    AAR  19970102  0.095  0.095  0.095  0.095   50000
3    ABA  19970102  6.890  6.940  6.890  6.930  153508
4    ABC  19970102  1.700  1.710  1.700  1.700   70000

In [128]:
price["rel_difference_close_open"] = price["open"]-price["open"]
price["rel_difference_close_close"] = price["open"]-price["open"]

price.head()

,ticker,date,open,high,low,close,volume,rel_difference_close_open,rel_difference_close_close
0,AAA,19970102,2.430,2.450,2.420,2.430,62508,0.0,0.0
1,AAD,19970102,0.740,0.760,0.740,0.750,10722,0.0,0.0
2,AAR,19970102,0.095,0.095,0.095,0.095,50000,0.0,0.0
3,ABA,19970102,6.890,6.940,6.890,6.930,153508,0.0,0.0
4,ABC,19970102,1.700,1.710,1.700,1.700,70000,0.0,0.0

In [132]:
index1 = 0
index2 = 0
counter = 0 #checks if it is the first day the ticker is open

for ticker in price.ticker.unique():
    indexes = price.loc[price["ticker"] == ticker].index
    for row in indexes:
        if counter == 0: #first day for the given ticker
            index1 = row
            index2 = row
            counter+=1
        else:
            counter+=1
            index2 = row
            price.at[row, "rel_difference_close_open"] = price.iloc[index2]["open"] - price.iloc[index1]["close"]
            price.at[row, "rel_difference_close_close"] = price.iloc[index2]["close"] - price.iloc[index1]["close"]
            index1 = row
    counter = 0 #reset for the next ticker

In [133]:
price

,ticker,date,open,high,low,close,volume,rel_difference_close_open,rel_difference_close_close
0,AAA,19970102,2.430,2.450,2.420,2.430,62508,0.000,0.000
1,AAD,19970102,0.740,0.760,0.740,0.750,10722,0.000,0.000
2,AAR,19970102,0.095,0.095,0.095,0.095,50000,0.000,0.000
3,ABA,19970102,6.890,6.940,6.890,6.930,153508,0.000,0.000
4,ABC,19970102,1.700,1.710,1.700,1.700,70000,0.000,0.000
5,ABD,19970102,0.085,0.085,0.085,0.085,2000,0.000,0.000
6,ABF,19970102,3.180,3.250,3.180,3.250,25050,0.000,0.000
7,ABG,19970102,4.244,4.250,4.230,4.250,7500,0.000,0.000
8,ABR,19970102,0.170,0.170,0.170,0.170,12500,0.000,0.000
9,ABT,19970102,0.075,0.075,0.075,0.075,25000,0.000,0.000
10,ACH,19970102,3.600,3.600,3.600,3.600,1489,0.000,0.000
11,ADB,19970102,4.260,4.350,4.260,4.340,34921,0.000,0.000
12,ADE,19970102,1.360,1.360,1.360,1.360,16831,0.000,0.000
13,ADF,19970102,0.120,0.120,0.120,0.120,10000,0.000,0.000
14,ADG,19970102,1.350,1.350,1.350,1.350,1000,0.000,0.000
15,ADH,19970102,1.060,1.060,1.060,1.060,7975,0.000,0.000
16,ADM,19970102,0.440,0.440,0.400,0.400,89992,0.000,0.000
17,ADN,19970102,0.475,0.600,0.465,0.530,583125,0.000,0.000
18,ADT,19970102,1.840,1.840,1.760,1.840,26679,0.000,0.000
19,ADX,19970102,0.325,0.325,0.320,0.325,45000,0.000,0.000
20,AEC,19970102,1.210,1.210,1.180,1.180,44900,0.000,0.000
21,AET,19970102,2.900,2.900,2.900,2.900,500,0.000,0.000
22,AEX,19970102,0.060,0.060,0.060,0.060,30000,0.000,0.000
23,AFI,19970102,2.160,2.170,2.150,2.150,118052,0.000,0.000
24,AFN,19970102,0.860,0.860,0.860,0.860,210,0.000,0.000
25,AFU,19970102,0.290,0.290,0.290,0.290,10000,0.000,0.000
26,AGA,19970102,0.215,0.215,0.215,0.215,8000,0.000,0.000
27,AGE,19970102,13.000,13.000,13.000,13.000,5000,0.000,0.000
28,AGL,19970102,7.020,7.200,7.000,7.200,161097,0.000,0.000
29,AGM,19970102,0.270,0.280,0.265,0.280,526500,0.000,0.000
...,...,...,...,...,...,...,...,...,...
6475440,XSO,20171229,2785.900,2786.200,2770.000,2770.000,0,0.000,-15.900
6475441,XST,20171229,0.012,0.012,0.012,0.012,1623566,0.000,0.000
6475442,XTD,20171229,0.041,0.041,0.041,0.041,7428,0.002,0.002
6475443,XTE,20171229,0.555,0.575,0.535,0.575,169860,0.020,0.040
6475444,XTJ,20171229,1326.000,1326.000,1307.800,1307.800,0,0.000,-18.200
6475445,XTL,20171229,3369.600,3373.400,3350.500,3360.100,0,0.000,-9.500
6475446,XTO,20171229,5005.900,5009.100,4975.400,4988.400,0,0.000,-17.500
6475447,XUJ,20171229,8310.100,8310.100,8221.500,8243.200,0,0.000,-66.900
6475448,XXJ,20171229,7307.900,7311.000,7258.000,7282.300,0,0.000,-25.600
6475449,YAL,20171229,0.130,0.130,0.125,0.125,340712,0.000,-0.005
6475450,YBR,20171229,0.140,0.140,0.140,0.140,15000,0.020,0.020
6475451,YMAX,20171229,9.140,9.150,9.130,9.150,16068,0.000,0.010
6475452,YNB,20171229,0.060,0.062,0.060,0.062,213600,0.000,0.002
6475453,YOJ,20171229,0.300,0.310,0.300,0.300,3677435,0.005,0.005
6475454,YPB,20171229,0.056,0.057,0.054,0.055,1129047,0.000,-0.001
6475455,ZEL,20171229,7.100,7.110,6.920,6.950,5951,0.380,0.230
6475456,ZEN,20171229,0.735,0.750,0.735,0.750,7193,0.000,0.015
6475457,ZEU,20171229,0.015,0.015,0.015,0.015,91145,0.000,0.000
6475458,ZGOL,20171229,16.470,16.500,16.470,16.500,124,0.230,0.260
6475459,ZIP,20171229,0.026,0.027,0.023,0.027,1060623,-0.002,-0.001
6475460,ZLD,20171229,0.093,0.096,0.091,0.093,1820533,0.002,0.002
6475461,ZMI,20171229,0.005,0.006,0.005,0.006,8723000,0.000,0.001
6475462,ZML,20171229,0.700,0.705,0.690,0.700,175772,0.000,0.000
6475463,ZNC,20171229,0.135,0.135,0.130,0.130,100000,0.005,0.000
6475464,ZNO,20171229,0.390,0.400,0.390,0.395,17985,0.005,0.010
6475465,ZNT,20171229,1.190,1.190,1.185,1.190,91789,0.010,0.010
6475466,ZOZI,20171229,10.750,10.750,10.750,10.750,3000,-0.130,-0.130
6475467,ZUSD,20171229,9.820,9.840,9.820,9.840,10003,-0.010,0.010
6475468,ZYB,20171229,0.016,0.019,0.016,0.018,32917443,0.001,0.003
6475469,ZYUS,20171229,12.650,12.650,12.620,12.620,7437,-0.080,-0.110

In [143]:
price.loc[price["ticker"] == "AAA"]

,ticker,date,open,high,low,close,volume,rel_difference_close_open,rel_difference_close_close
0,AAA,19970102,2.430,2.450,2.420,2.430,62508,0.000,0.000
731,AAA,19970103,2.410,2.410,2.370,2.390,149300,-0.020,-0.040
1493,AAA,19970106,2.374,2.374,2.340,2.340,399706,-0.016,-0.050
2313,AAA,19970107,2.328,2.328,2.200,2.230,2003228,-0.012,-0.110
3162,AAA,19970108,2.258,2.280,2.240,2.240,413900,0.028,0.010
3996,AAA,19970109,2.221,2.230,2.140,2.160,1813318,-0.019,-0.080
4815,AAA,19970110,2.200,2.220,2.160,2.160,1293116,0.040,0.000
5648,AAA,19970113,2.200,2.230,2.200,2.210,146650,0.040,0.050
6494,AAA,19970114,2.210,2.240,2.200,2.210,407140,0.000,0.000
7346,AAA,19970115,2.160,2.170,2.130,2.150,1599057,-0.050,-0.060
8190,AAA,19970116,2.150,2.150,2.110,2.150,923039,0.000,0.000
9057,AAA,19970117,2.170,2.200,2.170,2.200,344128,0.020,0.050
9937,AAA,19970120,2.250,2.260,2.220,2.250,348600,0.050,0.050
10839,AAA,19970121,2.210,2.260,2.200,2.250,517000,-0.040,0.000
11744,AAA,19970122,2.230,2.240,2.210,2.210,429200,-0.020,-0.040
12650,AAA,19970123,2.204,2.209,2.140,2.150,580102,-0.006,-0.060
13503,AAA,19970124,2.140,2.150,2.100,2.130,681903,-0.010,-0.020
14363,AAA,19970128,2.168,2.220,2.168,2.190,551800,0.038,0.060
15216,AAA,19970129,2.180,2.210,2.170,2.190,610900,-0.010,0.000
16075,AAA,19970130,2.250,2.260,2.230,2.250,564856,0.060,0.060
16948,AAA,19970131,2.203,2.240,2.180,2.240,269113,-0.047,-0.010
17801,AAA,19970203,2.220,2.220,2.200,2.210,273643,-0.020,-0.030
18650,AAA,19970204,2.240,2.260,2.220,2.230,963005,0.030,0.020
19515,AAA,19970205,2.230,2.280,2.230,2.280,558506,0.000,0.050
20372,AAA,19970206,2.283,2.390,2.280,2.390,890044,0.003,0.110
21215,AAA,19970207,2.394,2.394,2.190,2.240,2760363,0.004,-0.150
22070,AAA,19970210,2.250,2.250,2.190,2.190,1039362,0.010,-0.050
22921,AAA,19970211,2.156,2.180,2.080,2.091,1723664,-0.034,-0.099
23767,AAA,19970212,2.090,2.090,2.040,2.070,2856016,-0.001,-0.021
24638,AAA,19970213,2.167,2.190,2.130,2.160,1313966,0.097,0.090
...,...,...,...,...,...,...,...,...,...
6425461,AAA,20171116,50.110,50.120,50.110,50.120,58771,-0.010,0.000
6427116,AAA,20171117,50.120,50.130,50.120,50.130,148401,0.000,0.010
6428767,AAA,20171120,50.130,50.130,50.120,50.130,113919,0.000,0.000
6430453,AAA,20171121,50.130,50.140,50.130,50.140,91588,0.000,0.010
6432132,AAA,20171122,50.130,50.140,50.130,50.130,51312,-0.010,-0.010
6433808,AAA,20171123,50.130,50.140,50.130,50.130,85621,0.000,0.000
6435480,AAA,20171124,50.130,50.140,50.130,50.140,32091,0.000,0.010
6437116,AAA,20171127,50.140,50.150,50.140,50.140,35721,0.000,0.000
6438801,AAA,20171128,50.150,50.160,50.150,50.150,29715,0.010,0.010
6440487,AAA,20171129,50.150,50.160,50.150,50.150,111750,0.000,0.000
6442188,AAA,20171130,50.160,50.160,50.150,50.150,40380,0.010,0.000
6443855,AAA,20171201,50.070,50.080,50.070,50.080,43474,-0.080,-0.070
6445550,AAA,20171204,50.080,50.090,50.080,50.080,179422,0.000,0.000
6447261,AAA,20171205,50.090,50.090,50.080,50.080,25568,0.010,0.000
6448940,AAA,20171206,50.090,50.100,50.090,50.090,42619,0.010,0.010
6450589,AAA,20171207,50.090,50.100,50.090,50.100,18295,0.000,0.010
6452263,AAA,20171208,50.100,50.100,50.090,50.090,74689,0.000,-0.010
6453914,AAA,20171211,50.100,50.110,50.100,50.100,16011,0.010,0.010
6455574,AAA,20171212,50.100,50.110,50.100,50.100,34741,0.000,0.000
6457253,AAA,20171213,50.100,50.110,50.100,50.110,34394,0.000,0.010
6458921,AAA,20171214,50.110,50.120,50.110,50.120,21082,0.000,0.010
6460551,AAA,20171215,50.120,50.120,50.110,50.120,77020,0.000,0.000
6462210,AAA,20171218,50.120,50.130,50.120,50.130,78696,0.000,0.010
6463926,AAA,20171219,50.130,50.130,50.120,50.120,39450,0.000,-0.010
6465610,AAA,20171220,50.120,50.130,50.120,50.130,51869,0.000,0.010
6467287,AAA,20171221,50.130,50.140,50.130,50.130,87206,0.000,0.000
6468977,AAA,20171222,50.140,50.140,50.130,50.140,68009,0.010,0.010
6470624,AAA,20171227,50.160,50.160,50.140,50.150,46608,0.020,0.010
6472241,AAA,20171228,50.150,50.160,50.150,50.150,54305,0.000,0.000
6473842,AAA,20171229,50.150,50.160,50.150,50.160,15050,0.000,0.010

In [144]:
companies = pd.read_csv("asx-tickers.csv")
companies.head()

,ticker,company,industry
0,1AD,ADALTA LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences"
1,1AG,ALTERRA LIMITED,Commercial & Professional Services
2,1AL,ONEALL INTERNATIONAL LIMITED,Consumer Durables & Apparel
3,1PG,1-PAGE LIMITED,Software & Services
4,1ST,1ST GROUP LIMITED,Health Care Equipment & Services

In [10]:
df = pd.DataFrame([[1234, 'Customer A', '123 Street', np.nan],
               [1234, 'Customer A', np.nan, '333 Street'],
               [1233, 'Customer B', '444 Street', '333 Street'],
              [1233, 'Customer B', '444 Street', '666 Street']], columns=
['ID', 'Customer', 'Billing Address', 'Shipping Address'])

q1 = """SELECT ID FROM df """

print(ps.sqldf(q1, locals()))

     ID
0  1234
1  1234
2  1233
3  1233

In [145]:
pysql = lambda q: ps.sqldf(q, globals())
q1 = "SELECT price.ticker, price.open, price.close, companies.industry FROM price JOIN companies ON price.ticker = companies.ticker"
joined = pysql(q1)

In [148]:
joined

        ticker    open   close                                        industry
0          AAD   0.740   0.750                               Consumer Services
1          AAR   0.095   0.095                                       Materials
2          ABA   6.890   6.930                                           Banks
3          ABC   1.700   1.700                                       Materials
4          ABR   0.170   0.170                                       Materials
5          ABT   0.075   0.075                        Food, Beverage & Tobacco
6          ADH   1.060   1.060                                       Retailing
7          ADN   0.475   0.530                                       Materials
8          ADX   0.325   0.325                                          Energy
9          AFI   2.160   2.150                                      Not Applic
10         AGE  13.000  13.000                                          Energy
11         AGL   7.020   7.200                                       Utilities
12         AGR   1.350   1.370                                       Materials
13         AGS   0.300   0.300                                       Materials
14         AHX   2.510   2.550                Health Care Equipment & Services
15         ALK   0.550   0.560                                       Materials
16         ALL   3.200   3.250                               Consumer Services
17         AMC   7.960   8.060                                       Materials
18         AMG   0.079   0.080                                       Materials
19         AML   1.940   1.950                                       Materials
20         ANL   3.750   3.850                                       Materials
21         ANS   0.709   0.740                                       Materials
22         ANZ   7.850   7.940                                           Banks
23         AOF   1.060   1.060                                     Real Estate
24         AOG   1.250   1.300                                     Real Estate
25         AQS   0.160   0.170                               Consumer Services
26         ARA   0.280   0.280              Commercial & Professional Services
27         ARB   0.375   0.405                        Automobiles & Components
28         ARF   0.950   0.950                                     Real Estate
29         ARG   2.800   2.830                                      Not Applic
...        ...     ...     ...                                             ...
3413965    WRG   0.800   0.805                                       Utilities
3413966    WSA   3.250   3.240                                       Materials
3413967    WSI   0.025   0.025                                       Materials
3413968    WTC  14.250  14.150                             Software & Services
3413969    WTP   0.660   0.665                                   Capital Goods
3413970    WWI   0.024   0.024                                       Materials
3413971    XF1   0.670   0.675                             Software & Services
3413972    XIP   1.190   1.205              Commercial & Professional Services
3413973    XPE   0.007   0.007                             Software & Services
3413974    XRF   0.200   0.200                                   Capital Goods
3413975    XRO  28.190  28.660                             Software & Services
3413976    XST   0.012   0.012                                          Energy
3413977    XTD   0.041   0.041                                           Media
3413978    XTE   0.555   0.575                                   Capital Goods
3413979    YAL   0.130   0.125                                          Energy
3413980    YBR   0.140   0.140                          Diversified Financials
3413981    YNB   0.060   0.062                          Diversified Financials
3413982    YOJ   0.300   0.300                                       Materials
3413983    YPB   0.056   0.055              Commercial & Professional Services
3413984    ZEL   7.100   6.950                                          Energy
3413985    ZEN   0.735   0.750                                       Utilities
3413986    ZEU   0.015   0.015                                          Energy
3413987    ZIP   0.026   0.027                      Telecommunication Services
3413988    ZLD   0.093   0.093  Pharmaceuticals, Biotechnology & Life Sciences
3413989    ZMI   0.005   0.006                                       Materials
3413990    ZML   0.700   0.700                          Diversified Financials
3413991    ZNC   0.135   0.130                                       Materials
3413992    ZNO   0.390   0.395                                       Materials
3413993    ZNT   1.190   1.190                Health Care Equipment & Services
3413994    ZYB   0.016   0.018                             Software & Services

[3413995 rows x 4 columns]

In [149]:
q2 = "SELECT ticker, AVG(close) AS avg_close, AVG(rel_difference_close_open) AS avg_close_open, AVG(rel_difference_close_close) AS avg_close_close FROM price GROUP BY ticker" 
averaged = pysql(q2)

In [150]:
averaged

     ticker  avg_close  avg_close_open  avg_close_close
0       1AD   0.234384       -0.001059        -0.000148
1       1AG   0.045182       -0.000043        -0.000291
2       1AL   0.970978       -0.001783        -0.000261
3       1PG   1.558978        0.001141        -0.000291
4       1ST   0.072561        0.000029        -0.000306
5       3DM   0.087358        0.000861        -0.000021
6       3DP   0.036435        0.000201         0.000322
7       3PL   1.588073        0.001409        -0.000922
8       4CE   0.035857        0.000243         0.000226
9       4DS   0.030653        0.000159         0.000044
10      4WD   0.525573       -0.000907        -0.002600
11      5GN   0.359310        0.003276         0.003793
12      88E   0.029452        0.000345         0.000024
13      8CO   0.173042       -0.002609        -0.001025
14      8EC   0.974882       -0.000772        -0.000092
15      8IH   0.714941       -0.000139        -0.000059
16      9SP   0.141782        0.000434        -0.000189
17      A1C   0.223462       -0.001538         0.000000
18      A2M   2.422446        0.009113         0.009763
19      A3D   1.503497        0.011633         0.001358
20      AAA  33.595461        0.021569         0.021452
21      AAB   0.934833        0.000778        -0.001056
22      AAC   1.535739        0.001201         0.000076
23      AAD   1.687294        0.000072         0.000524
24      AAE   0.219060        0.000957        -0.000348
25      AAF   0.004930        0.000275         0.000242
26      AAG   0.207950       -0.000396         0.000066
27      AAH   1.062672       -0.001262         0.000404
28      AAI  26.039085       -0.093926        -0.099024
29      AAJ   0.044692       -0.000110        -0.000178
...     ...        ...             ...              ...
5148    ZEU   0.026625       -0.000079        -0.000342
5149    ZEX   0.023598       -0.000141        -0.000120
5150    ZFX   9.006345        0.016913         0.006032
5151    ZGL   0.233893        0.000426        -0.000067
5152    ZGM   0.095026       -0.000225        -0.000300
5153   ZGOL  16.543213        0.010725        -0.002415
5154    ZHE   0.221768       -0.002500        -0.001951
5155    ZIM   5.987067       -0.005119         0.001677
5156    ZIP   0.363342        0.002080        -0.000219
5157    ZLD   0.070239        0.001181         0.000254
5158    ZMG   0.093600       -0.001239        -0.000976
5159    ZMI   0.009982        0.000198        -0.000038
5160    ZML   0.642136        0.001979         0.000742
5161    ZNC   0.188757        0.000294        -0.000138
5162    ZNO   0.286105        0.002056         0.001327
5163    ZNT   1.090510        0.001205         0.001213
5164    ZNZ   4.503732        0.005694         0.005412
5165   ZOZI  10.364203        0.004444         0.002150
5166    ZPR   0.051380        0.000114        -0.000268
5167    ZRL   0.088528        0.000118        -0.000303
5168    ZTA   0.056065       -0.000173        -0.000188
5169    ZTL   0.618318        0.001754         0.001730
5170   ZUSD  10.054010       -0.001377        -0.001522
5171    ZYB   0.011916        0.000029        -0.000060
5172    ZYL   0.101954        0.000259        -0.000287
5173   ZYUS  12.479179        0.009058         0.000797
5174    ZZA   1.050000        0.000000         0.000000
5175    ZZB   1.040000        0.000000         0.000000
5176    ZZL   0.350000        0.000000         0.000000
5177    ZZP   1.000000        0.000000         0.000000

[5178 rows x 4 columns]

In [168]:
q3 = "SELECT ticker, date, close, (rel_difference_close_open/close) AS rel_difference_close_open, (rel_difference_close_close/close) AS rel_difference_close_close FROM price" 
relative_change = pysql(q3)

In [169]:
relative_change

,ticker,date,close,rel_difference_close_open,rel_difference_close_close
0,AAA,19970102,2.430,0.000000,0.000000
1,AAD,19970102,0.750,0.000000,0.000000
2,AAR,19970102,0.095,0.000000,0.000000
3,ABA,19970102,6.930,0.000000,0.000000
4,ABC,19970102,1.700,0.000000,0.000000
5,ABD,19970102,0.085,0.000000,0.000000
6,ABF,19970102,3.250,0.000000,0.000000
7,ABG,19970102,4.250,0.000000,0.000000
8,ABR,19970102,0.170,0.000000,0.000000
9,ABT,19970102,0.075,0.000000,0.000000
10,ACH,19970102,3.600,0.000000,0.000000
11,ADB,19970102,4.340,0.000000,0.000000
12,ADE,19970102,1.360,0.000000,0.000000
13,ADF,19970102,0.120,0.000000,0.000000
14,ADG,19970102,1.350,0.000000,0.000000
15,ADH,19970102,1.060,0.000000,0.000000
16,ADM,19970102,0.400,0.000000,0.000000
17,ADN,19970102,0.530,0.000000,0.000000
18,ADT,19970102,1.840,0.000000,0.000000
19,ADX,19970102,0.325,0.000000,0.000000
20,AEC,19970102,1.180,0.000000,0.000000
21,AET,19970102,2.900,0.000000,0.000000
22,AEX,19970102,0.060,0.000000,0.000000
23,AFI,19970102,2.150,0.000000,0.000000
24,AFN,19970102,0.860,0.000000,0.000000
25,AFU,19970102,0.290,0.000000,0.000000
26,AGA,19970102,0.215,0.000000,0.000000
27,AGE,19970102,13.000,0.000000,0.000000
28,AGL,19970102,7.200,0.000000,0.000000
29,AGM,19970102,0.280,0.000000,0.000000
...,...,...,...,...,...
6475440,XSO,20171229,2770.000,0.000000,-0.005740
6475441,XST,20171229,0.012,0.000000,0.000000
6475442,XTD,20171229,0.041,0.048780,0.048780
6475443,XTE,20171229,0.575,0.034783,0.069565
6475444,XTJ,20171229,1307.800,0.000000,-0.013917
6475445,XTL,20171229,3360.100,0.000000,-0.002827
6475446,XTO,20171229,4988.400,0.000000,-0.003508
6475447,XUJ,20171229,8243.200,0.000000,-0.008116
6475448,XXJ,20171229,7282.300,0.000000,-0.003515
6475449,YAL,20171229,0.125,0.000000,-0.040000
6475450,YBR,20171229,0.140,0.142857,0.142857
6475451,YMAX,20171229,9.150,0.000000,0.001093
6475452,YNB,20171229,0.062,0.000000,0.032258
6475453,YOJ,20171229,0.300,0.016667,0.016667
6475454,YPB,20171229,0.055,0.000000,-0.018182
6475455,ZEL,20171229,6.950,0.054676,0.033094
6475456,ZEN,20171229,0.750,0.000000,0.020000
6475457,ZEU,20171229,0.015,0.000000,0.000000
6475458,ZGOL,20171229,16.500,0.013939,0.015758
6475459,ZIP,20171229,0.027,-0.074074,-0.037037
6475460,ZLD,20171229,0.093,0.021505,0.021505
6475461,ZMI,20171229,0.006,0.000000,0.166667
6475462,ZML,20171229,0.700,0.000000,0.000000
6475463,ZNC,20171229,0.130,0.038462,0.000000
6475464,ZNO,20171229,0.395,0.012658,0.025316
6475465,ZNT,20171229,1.190,0.008403,0.008403
6475466,ZOZI,20171229,10.750,-0.012093,-0.012093
6475467,ZUSD,20171229,9.840,-0.001016,0.001016
6475468,ZYB,20171229,0.018,0.055556,0.166667
6475469,ZYUS,20171229,12.620,-0.006339,-0.008716

In [172]:
relative_change.to_csv("relative_change.csv")

In [174]:
rel = pd.read_csv("relative_change.csv")
rel

,Unnamed: 0,ticker,date,close,rel_difference_close_open,rel_difference_close_close
0,0,AAA,19970102,2.430,0.000000,0.000000
1,1,AAD,19970102,0.750,0.000000,0.000000
2,2,AAR,19970102,0.095,0.000000,0.000000
3,3,ABA,19970102,6.930,0.000000,0.000000
4,4,ABC,19970102,1.700,0.000000,0.000000
5,5,ABD,19970102,0.085,0.000000,0.000000
6,6,ABF,19970102,3.250,0.000000,0.000000
7,7,ABG,19970102,4.250,0.000000,0.000000
8,8,ABR,19970102,0.170,0.000000,0.000000
9,9,ABT,19970102,0.075,0.000000,0.000000
10,10,ACH,19970102,3.600,0.000000,0.000000
11,11,ADB,19970102,4.340,0.000000,0.000000
12,12,ADE,19970102,1.360,0.000000,0.000000
13,13,ADF,19970102,0.120,0.000000,0.000000
14,14,ADG,19970102,1.350,0.000000,0.000000
15,15,ADH,19970102,1.060,0.000000,0.000000
16,16,ADM,19970102,0.400,0.000000,0.000000
17,17,ADN,19970102,0.530,0.000000,0.000000
18,18,ADT,19970102,1.840,0.000000,0.000000
19,19,ADX,19970102,0.325,0.000000,0.000000
20,20,AEC,19970102,1.180,0.000000,0.000000
21,21,AET,19970102,2.900,0.000000,0.000000
22,22,AEX,19970102,0.060,0.000000,0.000000
23,23,AFI,19970102,2.150,0.000000,0.000000
24,24,AFN,19970102,0.860,0.000000,0.000000
25,25,AFU,19970102,0.290,0.000000,0.000000
26,26,AGA,19970102,0.215,0.000000,0.000000
27,27,AGE,19970102,13.000,0.000000,0.000000
28,28,AGL,19970102,7.200,0.000000,0.000000
29,29,AGM,19970102,0.280,0.000000,0.000000
...,...,...,...,...,...,...
6475440,6475440,XSO,20171229,2770.000,0.000000,-0.005740
6475441,6475441,XST,20171229,0.012,0.000000,0.000000
6475442,6475442,XTD,20171229,0.041,0.048780,0.048780
6475443,6475443,XTE,20171229,0.575,0.034783,0.069565
6475444,6475444,XTJ,20171229,1307.800,0.000000,-0.013917
6475445,6475445,XTL,20171229,3360.100,0.000000,-0.002827
6475446,6475446,XTO,20171229,4988.400,0.000000,-0.003508
6475447,6475447,XUJ,20171229,8243.200,0.000000,-0.008116
6475448,6475448,XXJ,20171229,7282.300,0.000000,-0.003515
6475449,6475449,YAL,20171229,0.125,0.000000,-0.040000
6475450,6475450,YBR,20171229,0.140,0.142857,0.142857
6475451,6475451,YMAX,20171229,9.150,0.000000,0.001093
6475452,6475452,YNB,20171229,0.062,0.000000,0.032258
6475453,6475453,YOJ,20171229,0.300,0.016667,0.016667
6475454,6475454,YPB,20171229,0.055,0.000000,-0.018182
6475455,6475455,ZEL,20171229,6.950,0.054676,0.033094
6475456,6475456,ZEN,20171229,0.750,0.000000,0.020000
6475457,6475457,ZEU,20171229,0.015,0.000000,0.000000
6475458,6475458,ZGOL,20171229,16.500,0.013939,0.015758
6475459,6475459,ZIP,20171229,0.027,-0.074074,-0.037037
6475460,6475460,ZLD,20171229,0.093,0.021505,0.021505
6475461,6475461,ZMI,20171229,0.006,0.000000,0.166667
6475462,6475462,ZML,20171229,0.700,0.000000,0.000000
6475463,6475463,ZNC,20171229,0.130,0.038462,0.000000
6475464,6475464,ZNO,20171229,0.395,0.012658,0.025316
6475465,6475465,ZNT,20171229,1.190,0.008403,0.008403
6475466,6475466,ZOZI,20171229,10.750,-0.012093,-0.012093
6475467,6475467,ZUSD,20171229,9.840,-0.001016,0.001016
6475468,6475468,ZYB,20171229,0.018,0.055556,0.166667
6475469,6475469,ZYUS,20171229,12.620,-0.006339,-0.008716